### ISSUE TITLE
Feature Request: NXDOMAIN

### ISSUE THREAD

**Issue by mubix** [mandatoryprogrammer/JudasDNS#1]
Awesome project! Testing it out one of the features I would love to see is a "ANY NXDOMAIN or failed response from the upstream servers gets this response"

**Comment by mandatoryprogrammer** [comment]
Ah, damn, why didn't I think of this use-case! Will definitely add this, I need this feature too hehe.

**Comment by mandatoryprogrammer** [comment]
Added this functionality to the tool via c572fe3ef4f30ed605f6c5f813abff77c0052adc, you can now create rules to match on the DNS RCODE. Still need to add a rule for TIMEOUT conditions though, will make a separate issue for that.
